# Generated by Django 3.1.3 on 2021-01-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cash_on',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AddField(
            model_name='orders',
            name='online_delivary',
            field=models.CharField(default='', max_length=111),
        ),
    ]
