# Generated by Django 3.1.3 on 2021-01-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210125_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='online_delivary',
            new_name='online_payment',
        ),
    ]
